### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shelu16** [AabyssZG/SpringBoot-Scan#1]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='spring-dev-vab.apps.grv.scbs.ch', port=80): Max retries exceeded with url: /actuator (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc216eb1160>: Failed to establish a new connection: [Errno 111] Connection refused'))

I think you have to wait for 10 second if not response then you have to move other target

**Comment by AabyssZG** [comment]
Thank you for your feedback. I have noticed this problem.
Let me think about how to solve this problem. It is expected to be solved in version 1.03.
My English is not good. If there is anything wrong with it, please understand.
