### ISSUE TITLE
扫描文件URL中针对inc文件夹下run.py中封装的file函数中try方法的优化建议.

### ISSUE THREAD

**Issue by aba666666** [AabyssZG/SpringBoot-Scan#10]
把结果保存为文件并扫描泄漏时,请验证网站是否存活或当前网络是否被拒绝访问,不要直接拼接路径就扫描,太影响效率

**Comment by aba666666** [comment]
try:
                        requests.packages.urllib3.disable_warnings()
                        r = requests.get(url=u, headers=newheader, timeout=6, allow_redirects=False, verify=False, proxies=proxies)  # 设置超时6秒
                        sleep(int(float(sleeps)))
                        if ((r.status_code == 200) and ('need login' not in r.text) and ('禁止访问' not in r.text) and (len(r.content) != 3318) and ('无访问权限' not in r.text) and ('认证失败' not in r.text)):
                            cprint("[+] 状态码%d" % r.status_code + ' ' + "信息泄露URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"red")
                            f2 = open("output.txt", "a")
                            f2.write(u + '\n')
                            f2.close()
                        elif(r.status_code == 200):
                            cprint("[+] 状态码%d" % r.status_code + ' ' + "但无法获取信息 URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"magenta")
                        else:
                            cprint("[-] 状态码%d" % r.status_code + ' ' + "无法访问URL为:" + u ,"yellow")
                    except KeyboardInterrupt:
                        print("Ctrl + C 手动终止了进程")
                        sys.exit()
                    except Exception as e:
                        cprint("[-] URL为 " + u + " 的目标积极拒绝请求，予以跳过！", "magenta")
请把inc里run.py中封装函数file中try这段代码,参考更新代码为:
                    try:
                        res = requests.get(url=url, headers=newheader, timeout=6, verify=False)
                        requests.packages.urllib3.disable_warnings()
                        if res.text != None:
                            try:
                                r = requests.get(url=u, headers=newheader, timeout=3, allow_redirects=False, verify=False)  # 设置超时6秒
                                sleep(int(float(sleeps)))
                                if ((r.status_code == 200) and ('need login' not in r.text) and ('禁止访问' not in r.text) and (len(r.content) != 3318) and ('无访问权限' not in r.text) and ('认证失败' not in r.text)):
                                    cprint("[+] 状态码%d" % r.status_code + ' ' + "信息泄露URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"red")
                                    f2 = open("output.txt", "a")
                                    f2.write(u + '\n')
                                    f2.close()
                                elif(r.status_code == 200):
                                    cprint("[+] 状态码%d" % r.status_code + ' ' + "但无法获取信息 URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"magenta")
                                else:
                                    cprint("[-] 状态码%d" % r.status_code + ' ' + "无法访问URL为:" + u ,"yellow")
                            except KeyboardInterrupt:
                                print("Ctrl + C 手动终止了进程")
                                sys.exit()
                    except Exception as e:
                        print("[-] URL为 " + url + " 的目标积极拒绝请求，予以跳过！", "magenta")
                        break
多加一个try来检测网站是否可以访问,能访问再测试,如果当前网络不能访问该网站,直接跳过路径探测,节约时间.

**Comment by AabyssZG** [comment]
好的，已经收到反馈了，非常感谢师傅的建议😍

**Comment by AabyssZG** [comment]
但是我没有理解，你写的代码当中，为什么还要多Get请求一次？
直接整体请求一次拿到需要的数据就行了，这样会更好吧。。
```python
                    try:
                        requests.packages.urllib3.disable_warnings()
                        r = requests.get(url=url, headers=newheader, timeout=6, allow_redirects=False, verify=False)  # 设置超时6秒
                        sleep(int(float(sleeps)))
                        if r.text != None:
                            if ((r.status_code == 200) and ('need login' not in r.text) and ('禁止访问' not in r.text) and (len(r.content) != 3318) and ('无访问权限' not in r.text) and ('认证失败' not in r.text)):
                                cprint("[+] 状态码%d" % r.status_code + ' ' + "信息泄露URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"red")
                                f2 = open("output.txt", "a")
                                f2.write(u + '\n')
                                f2.close()
                            elif(r.status_code == 200):
                                cprint("[+] 状态码%d" % r.status_code + ' ' + "但无法获取信息 URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"magenta")
                        else:
                            cprint("[-] 状态码%d" % r.status_code + ' ' + "无法访问URL为:" + u ,"yellow")
                    except KeyboardInterrupt:
                        print("Ctrl + C 手动终止了进程")
                        sys.exit()
                    except Exception as e:
                        cprint("[-] URL为 " + u + " 的目标积极拒绝请求，予以跳过！", "magenta")
                        break
```

**Comment by aba666666** [comment]
我的意思是先测试这个网站可以访问吗,网站都不能访问,再跑路径不是都不能访问吗

**Comment by aba666666** [comment]
好的

**Comment by aba666666** [comment]
![image](https://github.com/AabyssZG/SpringBoot-Scan/assets/113227651/bbd9f209-187b-4e18-88d0-a5e985c8b6d9)
有bug,如果请求不超时或不被重置,会一直请求该URL的/路径,师傅可以测试一下.

**Comment by aba666666** [comment]
> 但是我没有理解，你写的代码当中，为什么还要多Get请求一次？ 直接整体请求一次拿到需要的数据就行了，这样会更好吧。。
> 
> ```python
>                     try:
>                         requests.packages.urllib3.disable_warnings()
>                         r = requests.get(url=url, headers=newheader, timeout=6, allow_redirects=False, verify=False)  # 设置超时6秒
>                         sleep(int(float(sleeps)))
>                         if r.text != None:
>                             if ((r.status_code == 200) and ('need login' not in r.text) and ('禁止访问' not in r.text) and (len(r.content) != 3318) and ('无访问权限' not in r.text) and ('认证失败' not in r.text)):
>                                 cprint("[+] 状态码%d" % r.status_code + ' ' + "信息泄露URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"red")
>                                 f2 = open("output.txt", "a")
>                                 f2.write(u + '\n')
>                                 f2.close()
>                             elif(r.status_code == 200):
>                                 cprint("[+] 状态码%d" % r.status_code + ' ' + "但无法获取信息 URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"magenta")
>                         else:
>                             cprint("[-] 状态码%d" % r.status_code + ' ' + "无法访问URL为:" + u ,"yellow")
>                     except KeyboardInterrupt:
>                         print("Ctrl + C 手动终止了进程")
>                         sys.exit()
>                     except Exception as e:
>                         cprint("[-] URL为 " + u + " 的目标积极拒绝请求，予以跳过！", "magenta")
>                         break
> ```
![image](https://github.com/AabyssZG/SpringBoot-Scan/assets/113227651/bbd9f209-187b-4e18-88d0-a5e985c8b6d9)
有bug,如果请求不超时或不被重置,会一直请求该URL的/路径,师傅可以测试一下.

**Comment by aba666666** [comment]
![image](https://github.com/AabyssZG/SpringBoot-Scan/assets/113227651/cbd7ea97-bc0c-4bce-9a61-faa67ef82751)
我的代码也有问题,麻烦师傅重写以下把,主要是检测存活后才会一直请求路径就行了,怎么写无所谓,能实现就行.

**Comment by aba666666** [comment]
> 但是我没有理解，你写的代码当中，为什么还要多Get请求一次？ 直接整体请求一次拿到需要的数据就行了，这样会更好吧。。
> 
> ```python
>                     try:
>                         requests.packages.urllib3.disable_warnings()
>                         r = requests.get(url=url, headers=newheader, timeout=6, allow_redirects=False, verify=False)  # 设置超时6秒
>                         sleep(int(float(sleeps)))
>                         if r.text != None:
>                             if ((r.status_code == 200) and ('need login' not in r.text) and ('禁止访问' not in r.text) and (len(r.content) != 3318) and ('无访问权限' not in r.text) and ('认证失败' not in r.text)):
>                                 cprint("[+] 状态码%d" % r.status_code + ' ' + "信息泄露URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"red")
>                                 f2 = open("output.txt", "a")
>                                 f2.write(u + '\n')
>                                 f2.close()
>                             elif(r.status_code == 200):
>                                 cprint("[+] 状态码%d" % r.status_code + ' ' + "但无法获取信息 URL为:" + u + '    ' + "页面长度为:" + str(len(r.content)),"magenta")
>                         else:
>                             cprint("[-] 状态码%d" % r.status_code + ' ' + "无法访问URL为:" + u ,"yellow")
>                     except KeyboardInterrupt:
>                         print("Ctrl + C 手动终止了进程")
>                         sys.exit()
>                     except Exception as e:
>                         cprint("[-] URL为 " + u + " 的目标积极拒绝请求，予以跳过！", "magenta")
>                         break
> ```

别动源代码,添加break即可
![image](https://github.com/AabyssZG/SpringBoot-Scan/assets/113227651/26c8f3f5-bd54-4b0b-a5fa-fbc8b9a57e66)

**Comment by AabyssZG** [comment]
收到，已经加上了，感谢师傅的反馈😘

**Comment by AabyssZG** [comment]
那应该没问题了哈哈，如果还有问题，欢迎师傅继续提Issues，感谢师傅😍
