### ISSUE TITLE
SpringBoot-Scan的一些建议

### ISSUE THREAD

**Issue by chinatelacom** [AabyssZG/SpringBoot-Scan#13]
你好，作者！
我觉得这个脚本是不是可以添加一些爬虫功能    而不是只爆破字典中的内容   比如一些spring未授权环境下  访问/actuator/  里面会有一些非字典中的内容如  /actuator/nacosconfig 、/actuator/nacosdiscovery等   这种情况下感觉加上爬虫爬取/actuator/会好一些

**Comment by chinatelacom** [comment]
还有就是有些网站访问不存在地址时返回的响应码为200  这时候会导致 Dir.txt中的所有内容都会存储到urlout.txt中      可不可以加上一个判断  如果返回包的hash一致则不保存
import hashlib
    encountered_hashes = set()
    valid_pages = []
                content_hash = hashlib.md5(r.content).hexdigest()
                    if content_hash not in encountered_hashes:
                        # 如果是新的哈希值，保存页面内容并记录哈希值
                        valid_pages.append(r.content)
                        encountered_hashes.add(content_hash)
                        f2 = open("urlout.txt", "a")
                        f2.write(u + '\n')
                        f2.close()
                    else:
                        # 如果哈希值已存在，忽略该页面内容
                        print(f"已存在{url}")

**Comment by AabyssZG** [comment]
已经收到师傅的反馈，我会再优化优化相关的内容🤩
之前就已经想到对页面Hash进行校验的想法哈哈~

**Comment by chinatelacom** [comment]
嗯嗯   期待更新😁

**Comment by AabyssZG** [comment]
版本已经更新，欢迎查看[V2.55](https://github.com/AabyssZG/SpringBoot-Scan/releases/tag/2.55)版本，感谢师傅的反馈😍
目前对端点爆破模块进行优化，对页面进行Hash计算，如果发现页面Hash相同的情况就不导入到 `urlout.txt`，但是爬虫这块我还在考虑，后续可以尝试一下
