### ISSUE TITLE
扫出来了这个webjars/springfox-swagger-ui/swagger-ui-standalone-preset.js?v=2.9.2请问有危害吗没看出来怎么利用

### ISSUE THREAD

**Issue by lishixin7777** [AabyssZG/SpringBoot-Scan#20]
![图片](https://github.com/AabyssZG/SpringBoot-Scan/assets/123936946/3e25b7ed-4e1e-42a3-b390-9b00c790202c)

**Comment by AabyssZG** [comment]
这个应该是 `swagger-ui` 调用的JavaScript文件，用于证明 `swagger-ui` 接口页面的存在，需要找到 `swagger-ui` 的接口页面才能对其进行API的各种测试和利用

**Comment by lishixin7777** [comment]
常用路径都没找到swaggger-ui的接口页面，呢这个不就没用了吗

**Comment by AabyssZG** [comment]
那就要看你能不能FUZZ出 `swaggger-ui` 的接口页面路径了，FUZZ不出来就没用了
