### ISSUE TITLE
扫描报错

### ISSUE THREAD

**Issue by moosee19** [AabyssZG/SpringBoot-Scan#5]
在扫描时发生错误，实际上应该存在这个目录，用其他扫描工具是正常的
![111](https://github.com/AabyssZG/SpringBoot-Scan/assets/41313314/cee45bcf-172c-459b-850e-2abe5c7ffdd8)

**Comment by AabyssZG** [comment]
因为我这边使用了try循环，所以有两种可能性：1、请求超时 2、内部报错了
能否提供一下目标地址；或者修改一下代码，将try循环去掉，然后反馈一下报错信息，这样方便我定位问题以及原因
同时感谢师傅的关注和支持，万分感谢~

**Comment by AabyssZG** [comment]
由于太久没回复，且没有补充相关的日志和运行信息，暂且作无问题处理
如果师傅后续还有问题，可以继续提issues😄
