### ISSUE TITLE
安装库后，还是报错

### ISSUE THREAD

**Issue by Depart0** [AabyssZG/SpringBoot-Scan#7]
Traceback (most recent call last):
  File "E:\Tools\SpringBoot-Scan-main\SpringBoot-Scan.py", line 7, in <module>
    from inc import output, console, run ,proxycheck
  File "E:\Tools\SpringBoot-Scan-main\inc\console.py", line 4, in <module>
    from inc import output,run,vul,springcheck
  File "E:\ools\SpringBoot-Scan-main\inc\springcheck.py", line 4, in <module>
    from inc import output,run,vul,console
ImportError: cannot import name 'vul' from 'inc' (unknown location)

**Comment by Depart0** [comment]
环境：win10、Python 3.11.1

**Comment by AabyssZG** [comment]
在 `E:\Tools\SpringBoot-Scan-main\` 路径下，找到 `inc` 这个文件夹，查看里面有没有名为 `vul.py` 这个文件
如果没有，请重新下载 `Realease` 并解压

**Comment by AabyssZG** [comment]
因为存在漏洞利用信息，所以可能是本地杀毒软件把 `vul.py` 给查杀了，师傅可以看看

**Comment by Depart0** [comment]
> 因为存在漏洞利用信息，所以可能是本地杀毒软件把 `vul.py` 给查杀了，师傅可以看看

是这样，得关windowsdefender😂。

**Comment by AabyssZG** [comment]
那师傅应该没啥疑问了吧？哈哈😄

**Comment by Depart0** [comment]
> 那师傅应该没啥疑问了吧？哈哈😄

没问题了，谢谢师傅。star点起哈哈

**Comment by AabyssZG** [comment]
感谢师傅的关注和支持，后续有问题可以再提issues🥰
